# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DMSwift
pod 'RxCocoa', '~> 3.6.1'
pod 'RxSwift', '~> 3.6.1'
end
